# Generated by Django 5.1.4 on 2026-08-06 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreWebhookEvent',
            fields=[
                ('event_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('source', models.CharField(blank=True, default='', max_length=16)),
                ('app_user_id', models.CharField(blank=True, default='', max_length=255)),
                ('product_id', models.CharField(blank=True, default='', max_length=255)),
                ('outcome', models.CharField(blank=True, default='', max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['app_user_id', '-received_at'], name='billing_sto_app_use_2192d7_idx')],
            },
        ),
    ]
