# Generated by Django 5.1.4 on 2026-05-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='conversation',
            new_name='assistant_c_user_id_6ae267_idx',
            old_name='assistant_c_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='assistant_m_convers_da4640_idx',
            old_name='assistant_m_conv_idx',
        ),
        migrations.RenameIndex(
            model_name='usageday',
            new_name='assistant_u_user_id_72dcac_idx',
            old_name='assistant_u_user_id_idx',
        ),
        migrations.AlterField(
            model_name='usageday',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
