# Generated by Django 5.1.4 on 2026-05-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_accountprofile_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='usageday',
            name='deep_messages',
            field=models.IntegerField(default=0),
        ),
    ]
