# Generated by Django 5.1.4 on 2026-06-18 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0009_accountprofile_cancel_at_period_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='beta_cohort',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='beta_enrolled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='beta_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('reclaimed', 'Reclaimed'), ('manually_paused', 'Manually paused'), ('manually_killed', 'Manually killed')], db_index=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='billing_exempt_reason',
            field=models.CharField(blank=True, choices=[('beta', 'Beta'), ('friend', 'Friend'), ('investor', 'Investor'), ('partner', 'Partner'), ('manual', 'Manual')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='billing_exempt_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='reclaim_warned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
