# Generated by Django 5.1.4 on 2026-08-06 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0011_backfill_beta_cohort'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='billing_source',
            field=models.CharField(blank=True, choices=[('stripe', 'Stripe (web)'), ('apple', 'App Store'), ('google', 'Google Play')], db_index=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='store_product_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='store_transaction_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
