# Generated by Django 5.1.4 on 2026-08-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0012_accountprofile_billing_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountprofile',
            name='store_product_id',
        ),
        migrations.RemoveField(
            model_name='accountprofile',
            name='store_transaction_id',
        ),
        migrations.RemoveField(
            model_name='accountprofile',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='accountprofile',
            name='stripe_price_id',
        ),
        migrations.RemoveField(
            model_name='accountprofile',
            name='stripe_subscription_id',
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='billing_customer_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='billing_product_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='billing_transaction_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='accountprofile',
            name='billing_source',
            field=models.CharField(blank=True, choices=[('web', 'Web (RevenueCat Web Billing)'), ('apple', 'App Store'), ('google', 'Google Play'), ('stripe', 'Stripe directo (deprecado)')], db_index=True, default='', max_length=16),
        ),
    ]
