# Generated by Django 5.1.4 on 2026-08-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0013_remove_accountprofile_store_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountprofile',
            name='billing_source',
            field=models.CharField(blank=True, choices=[('web', 'Web (RevenueCat Web Billing)'), ('apple', 'App Store'), ('google', 'Google Play')], db_index=True, default='', max_length=16),
        ),
    ]
