# Generated by Django 5.1.4 on 2026-05-12 16:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('entity_type', models.CharField(choices=[('project', 'Project'), ('task', 'Task'), ('idea', 'Idea')], max_length=16)),
                ('entity_id', models.UUIDField()),
                ('entity_title', models.CharField(blank=True, default='', max_length=500)),
                ('action', models.CharField(choices=[('created', 'Created'), ('deleted', 'Deleted'), ('status_changed', 'Status changed'), ('due_date_changed', 'Due date changed'), ('promoted', 'Promoted')], max_length=24)),
                ('project_id', models.UUIDField(blank=True, null=True)),
                ('target_project_id', models.UUIDField(blank=True, null=True)),
                ('previous_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['user_id', '-created'], name='core_activi_user_id_62345b_idx'), models.Index(fields=['user_id', 'entity_type'], name='core_activi_user_id_4fb76f_idx'), models.Index(fields=['user_id', 'project_id'], name='core_activi_user_id_588345_idx')],
            },
        ),
    ]
