# Generated by Django 5.1.4 on 2026-05-12 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_activity_unify'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activity',
            new_name='core_activi_user_id_39b9e2_idx',
            old_name='core_activity_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='activity',
            new_name='core_activi_user_id_b35b54_idx',
            old_name='core_activity_user_kind_idx',
        ),
        migrations.RenameIndex(
            model_name='activity',
            new_name='core_activi_user_id_555ebb_idx',
            old_name='core_activity_user_project_idx',
        ),
    ]
