# Generated by Django 5.1.4 on 2026-06-11 21:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_onboarding_example_seeded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='kind',
            field=models.CharField(choices=[('note', 'Note'), ('project_created', 'Project created'), ('project_deleted', 'Project deleted'), ('project_status_changed', 'Project status changed'), ('project_due_date_changed', 'Project due date changed'), ('task_created', 'Task created'), ('task_completed', 'Task completed'), ('task_deleted', 'Task deleted'), ('task_due_date_changed', 'Task due date changed'), ('idea_created', 'Idea created'), ('idea_deleted', 'Idea deleted'), ('idea_promoted', 'Idea promoted'), ('routine_created', 'Routine created'), ('routine_completed', 'Routine completed'), ('routine_deleted', 'Routine deleted'), ('quick_note_created', 'Quick note created'), ('quick_note_deleted', 'Quick note deleted')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='QuickNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('pinned', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quick_notes', to='core.category')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quick_notes', to='core.project')),
            ],
            options={
                'ordering': ['-pinned', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='NoteSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('heading', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('position', models.PositiveIntegerField(default=0)),
                ('collapsed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.quicknote')),
            ],
            options={
                'ordering': ['position', 'created'],
            },
        ),
        migrations.AddIndex(
            model_name='quicknote',
            index=models.Index(fields=['user_id', '-updated_at'], name='core_quickn_user_id_5300ea_idx'),
        ),
        migrations.AddIndex(
            model_name='quicknote',
            index=models.Index(fields=['user_id', 'category'], name='core_quickn_user_id_bb520b_idx'),
        ),
        migrations.AddIndex(
            model_name='quicknote',
            index=models.Index(fields=['user_id', 'project'], name='core_quickn_user_id_83bd73_idx'),
        ),
        migrations.AddIndex(
            model_name='notesection',
            index=models.Index(fields=['note', 'position'], name='core_notese_note_id_be2a15_idx'),
        ),
    ]
