# Generated by Django 5.1.4 on 2026-06-13 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_activity_kind_quicknote_notesection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField()),
                ('date', models.DateField()),
                ('source', models.CharField(choices=[('web', 'Web app'), ('mobile', 'Mobile app'), ('connector', 'Claude connector'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['user_id', '-date'], name='core_intera_user_id_07a64b_idx'), models.Index(fields=['date', 'source'], name='core_intera_date_bc7f04_idx')],
                'constraints': [models.UniqueConstraint(fields=('user_id', 'date', 'source'), name='unique_interaction_per_user_day_source')],
            },
        ),
    ]
