# Generated by Django 5.1.4 on 2026-06-13 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_interactionday'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthClient',
            fields=[
                ('client_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('client_name', models.CharField(blank=True, default='', max_length=255)),
                ('redirect_uris', models.JSONField(default=list)),
                ('token_endpoint_auth_method', models.CharField(default='none', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OAuthAuthorizationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('user_id', models.UUIDField()),
                ('redirect_uri', models.TextField()),
                ('code_challenge', models.CharField(max_length=255)),
                ('code_challenge_method', models.CharField(default='S256', max_length=12)),
                ('scope', models.CharField(blank=True, default='', max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.oauthclient')),
            ],
        ),
        migrations.CreateModel(
            name='OAuthRefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('user_id', models.UUIDField(db_index=True)),
                ('scope', models.CharField(blank=True, default='', max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.oauthclient')),
            ],
            options={
                'indexes': [models.Index(fields=['user_id', 'client'], name='core_oauthr_user_id_b62f9b_idx')],
            },
        ),
    ]
