# Generated by Django 5.1.4 on 2026-06-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_oauthclient_oauthauthorizationcode_oauthrefreshtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthConnectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(db_index=True)),
                ('client_id', models.CharField(max_length=64)),
                ('client_name', models.CharField(blank=True, default='', max_length=255)),
                ('event', models.CharField(choices=[('authorized', 'Authorized'), ('token_refreshed', 'Token refreshed'), ('revoked', 'Revoked by user'), ('admin_revoked', 'Revoked by admin')], max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['user_id', '-created'], name='core_oauthc_user_id_0651dd_idx'), models.Index(fields=['-created'], name='core_oauthc_created_a61b63_idx')],
            },
        ),
    ]
