# Generated by Django 5.1.4 on 2026-06-16 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_oauthconnectionevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraveyardInsight',
            fields=[
                ('user_id', models.UUIDField(primary_key=True, serialize=False)),
                ('body', models.TextField(blank=True, default='')),
                ('deaths_count', models.PositiveIntegerField(default=0)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
                ('is_stale', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='killed_ai_reflection',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='killed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='killed_learnings',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='project',
            name='killed_reason',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='project',
            name='killed_would_restart',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='paused_blocker',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='project',
            name='paused_context',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='paused_next_action',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='stalled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('idea', 'Idea'), ('active', 'Active'), ('stalled', 'Stalled'), ('paused', 'Paused'), ('launched', 'Launched'), ('killed', 'Killed'), ('archived', 'Archived')], default='idea', max_length=20),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user_id', 'status', 'last_activity'], name='idx_project_status_activity'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'last_activity'], name='idx_project_stalled_sweep'),
        ),
    ]
