# Generated by Django 5.1.4 on 2026-06-18 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_graveyardinsight_project_killed_ai_reflection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StalledSweepState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('cutoff_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
