# Generated by Django 5.1.4 on 2026-06-18 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_stalledsweepstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('value', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
