# Generated by Django 5.1.4 on 2026-06-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_routine_calendar_event_id_routine_duration_minutes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICloudCalendarCredential',
            fields=[
                ('user_id', models.UUIDField(primary_key=True, serialize=False)),
                ('apple_id', models.CharField(blank=True, default='', max_length=320)),
                ('app_password', models.TextField()),
                ('calendar_url', models.CharField(blank=True, default='', max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
