# Generated by Django 5.1.4 on 2026-06-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_task_parked_due_date_task_parked_due_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
