# Generated by Django 5.1.4 on 2026-09-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_project_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='client_token',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(('client_token', ''), _negated=True), fields=('user_id', 'client_token'), name='uniq_user_client_token'),
        ),
    ]
