"""Typed accessors for the global `AppConfig` key/value table.

Single source of the beta-lifecycle knobs. `DEFAULTS` is the canonical default
set — the seed data migration writes these rows, and the getters fall back to
them if a row is missing, so the system is correct even before/around seeding.

No caching: the table is tiny and reads are infrequent (signup reads 2 keys per
new user; the daily cron reads each key once per run). Correctness over a cache
that would need cross-process invalidation under gunicorn.
"""

from __future__ import annotations

from typing import Any

DEFAULTS: dict[str, Any] = {
    # Master switch: when true, no product email is actually sent — every send
    # is logged to email_sends(dry_run=True) for admin preview instead.
    "dry_run": True,
    # Beta enrollment gate.
    "beta_enrollment_open": False,
    "beta_spot_cap": 50,
    # Engagement signals. project_status_changed is included, but the cron's
    # significant_events_q() additionally excludes transitions to 'stalled'
    # (auto-generated by the Graveyard sweep) — see docs/PROPOSAL.md §0.
    "significant_event_kinds": [
        "project_created",
        "project_status_changed",
        "task_created",
        "task_completed",
        "idea_created",
        "idea_promoted",
        "routine_created",
        "routine_completed",
        "quick_note_created",
    ],
    # Ghost path (never engaged): nudge days then reclaim.
    "ghost_nudge_days": [3, 7, 14],
    "ghost_reclaim_day": 21,
    # Active tiers (was-active then lapsed): re-engagement nudge days.
    "reengage_days": [7, 14],
    # Reclaim thresholds (days inactive) by tier.
    "brief_reclaim_days": 60,
    "dormant_reclaim_days": 180,
    # Activity span (last - first significant event) to count as "established".
    "established_min_activity_days": 30,
    # Reclaim only fires once reclaim_warned_at is this many days old.
    "reclaim_warn_grace_days": 7,
}


def _raw(key: str, default: Any = None) -> Any:
    from core.models import AppConfig

    row = AppConfig.objects.filter(key=key).values_list("value", flat=True).first()
    if row is not None:
        return row
    if key in DEFAULTS:
        return DEFAULTS[key]
    return default


def get(key: str, default: Any = None) -> Any:
    return _raw(key, default)


def get_bool(key: str, default: bool = False) -> bool:
    return bool(_raw(key, default))


def get_int(key: str, default: int = 0) -> int:
    return int(_raw(key, default))


def get_list(key: str, default: list | None = None) -> list:
    val = _raw(key, default if default is not None else [])
    return list(val) if val is not None else []


def set(key: str, value: Any) -> None:
    """Upsert a config row. Caller is responsible for audit logging."""
    from core.models import AppConfig

    AppConfig.objects.update_or_create(key=key, defaults={"value": value})
