# Generated by Django 5.1.4 on 2026-05-29 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='announcement',
            new_name='announcemen_status_5b566b_idx',
            old_name='announcemen_status_8b5e62_idx',
        ),
    ]
