"""Sweep test: every admin mutation must reject non-admin callers.

Generated by introspecting the merged schema. If a new admin mutation
gets added without going through `_admin_user_id`, this test fails.
"""

import re

import pytest

from core.assistant.models import AccountProfile
from core.schema import schema


ADMIN_MUTATION_PATTERN = re.compile(r"^\s*admin[A-Z]\w+\s*[\(:]")


def _list_admin_mutation_names() -> list[str]:
    sdl = str(schema)
    in_mutation_type = False
    out: list[str] = []
    for line in sdl.splitlines():
        stripped = line.strip()
        if stripped.startswith("type Mutation {"):
            in_mutation_type = True
            continue
        if in_mutation_type and stripped == "}":
            break
        if not in_mutation_type:
            continue
        match = re.match(r"(admin[A-Z]\w+)\s*[\(:]", stripped)
        if match:
            out.append(match.group(1))
    return out


@pytest.mark.django_db
def test_every_admin_mutation_rejects_non_admin(execute_query, user_a):
    AccountProfile.objects.create(user_id=user_a, is_admin=False)
    names = _list_admin_mutation_names()
    assert len(names) > 0, "No admin mutations found — sweep would silently pass"

    # Use a structurally-valid but minimal mutation call. We don't care
    # whether the args validate — the auth check should fire first and
    # raise FORBIDDEN before resolver bodies run.
    blocked = []
    for name in names:
        # Build a minimal mutation document. Strawberry returns errors
        # for required args, but FORBIDDEN should still trigger because
        # our resolver calls `_admin_user_id(info)` as the first line.
        doc = f"mutation {{ {name} }}"
        result = execute_query(doc, user_id=user_a)
        # Either invalid args (validation error) or FORBIDDEN (auth).
        # We require that NO mutation produces a successful data response
        # for a non-admin caller. If validation rejects it, that's also
        # acceptable — the mutation never executed.
        if result.errors is None and result.data and result.data.get(name) not in (None, False):
            blocked.append((name, result.data))

    assert not blocked, f"Admin mutations callable by non-admin: {blocked}"
