# Generated by Django 5.1.4 on 2026-05-20 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_help_resources'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='helpresource',
            new_name='cms_helpres_status_805613_idx',
            old_name='cms_helpres_status_a1c2b3_idx',
        ),
    ]
