# Generated by Django 5.1.4 on 2026-05-13 20:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_user_id', models.UUIDField(db_index=True)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('target_type', models.CharField(blank=True, default='', max_length=64)),
                ('target_id', models.CharField(blank=True, default='', max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['actor_user_id', '-created'], name='admin_api_a_actor_u_3c2016_idx'), models.Index(fields=['target_type', 'target_id'], name='admin_api_a_target__f9a346_idx')],
            },
        ),
    ]
