# Generated by Django 5.1.4 on 2026-05-09 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationsettings_locale'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_status_d8d933_idx',
            old_name='notif_status_sched_idx',
        ),
    ]
