# Generated by Django 5.1.4 on 2026-05-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notificationsettings_palette'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='daily_digest_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='daily_digest_hour',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('weekly_digest', 'Weekly digest'), ('daily_digest', 'Daily pending tasks'), ('sleeping_alert', 'Sleeping project alert'), ('due_reminder', 'Due-date reminder'), ('manual', 'Manual / admin')], max_length=32),
        ),
    ]
