# Generated by Django 5.1.4 on 2026-05-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_notificationsettings_daily_digest_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationsettings',
            name='due_reminder_lead_hours',
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='due_reminder_hour',
            field=models.PositiveSmallIntegerField(default=19),
        ),
    ]
