# Generated by Django 5.2.4 on 2026-06-06 18:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_remove_notificationsettings_due_reminder_lead_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='push_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('expo', 'Push (Expo)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationlink',
            name='channel',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('expo', 'Push (Expo)')], max_length=20),
        ),
        migrations.CreateModel(
            name='ExpoPushToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('device_id', models.CharField(max_length=128)),
                ('token', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user_id', 'device_id'), name='unique_expo_token_per_device')],
            },
        ),
    ]
