# Generated by Django 5.1.4 on 2026-06-18 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_fase8_push'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSend',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('email_id', models.CharField(max_length=32)),
                ('episode_key', models.CharField(blank=True, default='', max_length=32)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('dry_run', 'Dry run')], max_length=8)),
                ('dry_run', models.BooleanField(default=True)),
                ('resend_message_id', models.CharField(blank=True, default='', max_length=255)),
                ('error', models.TextField(blank=True, default='')),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['user_id', 'email_id'], name='notificatio_user_id_11ff12_idx'), models.Index(fields=['status', '-created'], name='notificatio_status_5d2a5a_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('dry_run', False)), fields=('user_id', 'email_id', 'episode_key'), name='uniq_real_email_send')],
            },
        ),
    ]
