# Generated by Django 5.1.4 on 2026-06-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_emailsend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsend',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('dry_run', 'Dry run'), ('suppressed', 'Suppressed')], max_length=12),
        ),
    ]
