# Generated by Django 5.1.4 on 2026-06-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_suppress_welcome_existing'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='calendar_feed_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='calendar_sync_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='calendar_sync_routines',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='calendar_sync_tasks',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='google_calendar_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
