# Generated by Django 5.1.4 on 2026-06-09 02:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('topic', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('platform', models.CharField(choices=[('web', 'Web'), ('app', 'App')], default='web', max_length=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('archived', 'Archived')], db_index=True, default='new', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['status', '-created'], name='feedback_bu_status_8880a7_idx')],
            },
        ),
    ]
